import os

SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
CELERY_BROKER_URL="sqla+" + os.environ['DATABASE_URL']
CELERY_RESULT_BACKEND="db+" + os.environ['DATABASE_URL']
