version: "3.1"

services:
  app:
    ports:
      - 8080:8080
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ${PWD}/:/home/user/app
    environment:
      DATABASE_URL: postgresql://${PGUSER:-user}:${PGPASSWORD:-pass}@postgres:5432/${PGDATABASE:-hp}
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PGUSER:-user}
      POSTGRES_DB: ${PGDATABASE:-hp}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pass}
