version: "3.1"

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PGUSER:-user}
      POSTGRES_DB: ${PGDATABASE:-hp}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pass}
