version: "3.1"

services:
  app:
    ports:
      - 8000:80
    build:
      context: .
    depends_on:
      - db
      - rds
    volumes:
      - ${HOME}/.aws/config:/home/user/.aws/config
      - ${PWD}/:/home/user/app
  rds:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      ENGINE: PostgreSQLJDBC
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports:
      - 9228:80
  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports:
      - 5432:5432
