# fly.toml file generated for dream on 2021-07-18T13:58:37+02:00

app = "dream"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  auto_rollback = true

[deploy]
  release_command = "flask db upgrade"

[processes]
  web = "gunicorn 'run_app:app' -b 0.0.0.0:8080"
  worker = "celery --app 'run_app:celery' worker"

[statics]
  processes = ["web"] # this service only applies to the web block
  guest_path = "/home/user/app/app/static"
  url_prefix = "/static"

[[services]]
  processes = ["web"] # this service only applies to the web block
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
