[tool.pytest.ini_options]
cache_dir="/home/user/.pytest/cache"

[tool.poetry]
name = "dream"
version = "0.1.0"
description = ""
authors = ["Craig Mulligan <hey@hobochild.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask-Migrate="*"
Flask-Script="*"
Flask-SQLAlchemy="*"
Flask="*"
requests="*"
SQLAlchemy-Utils="*"
gunicorn="*"
bcrypt = "*"
celery = "*"
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
pytest="*"
pytest-testmon="*"
pytest-watch="*"
pytest-flask = "^1.2.0"
watchdog = {extras = ["watchmedo"], version = "^2.1.6"}
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = "flasksqlamypy"

[[tool.mypy.overrides]]
module="flask_migrate,celery,sqlalchemy_utils.*"
ignore_missing_imports = true
