name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8
      - run: poetry install
      - run: poetry run flask dev db
      - run: poetry run flask dev fmt --check
      - run: poetry run flask dev mypy 
      - run: poetry run flask dev test
