name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: poetry install
      - run: poetry run flask dev db
      - run: poetry run flask dev fmt --check
      - run: poetry run flask dev test
