name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./task build
      - run: ./task fmt --check
      - run: ./task test
